FROM python:3.7-slim

COPY ./python_modules/ /tmp/python_modules/

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagit and dagster-daemon, and to load the DagsterInstance

RUN pip install \
    -e python_modules/dagster \
    -e python_modules/libraries/dagster-postgres \
    -e python_modules/libraries/dagster-docker

# Add repository code
WORKDIR /opt/dagster/app
COPY repo.py /opt/dagster/app
