from typing import Any, Dict, Optional

from dagster import check, usable_as_dagster_type

from ..types import DbtResult


@usable_as_dagster_type
class DbtCliResult(DbtResult):
    """The results of executing a dbt command, along with additional metadata about the dbt CLI
    process that was run.

    We recommend that you construct an instance of :class:`DbtCliResult
    <dagster_dbt.DbtCliResult>` by using the class method:func:`from_dict
    <dagster_dbt.DbtCliResult.from_dict>`.

    When using the dbt CLI, the CLI run results are typically parsed from the shell's standard
    output and ``target/run_results.json``, which is generated by dbt.


    If the executed dbt command is either ``run`` or ``test``, then the ``.num_*`` attributes will
    contain non-``None`` integer values. Otherwise, they will be ``None``.
    """

    def __init__(
        self,
        *args,
        command: str,
        return_code: int,
        raw_output: str,
        num_pass: Optional[int] = None,
        num_warn: Optional[int] = None,
        num_error: Optional[int] = None,
        num_skip: Optional[int] = None,
        num_total: Optional[int] = None,
        **kwargs
    ):
        """Constructor

        Args:
            command (str): The full shell command that was executed.
            return_code (int): The return code of the dbt CLI process.
            raw_output (str): The raw output (``stdout``) of the dbt CLI process.
            num_pass (Optional[int]): The number of dbt nodes (models) that passed.
            num_warn (Optional[int]): The number of dbt nodes (models) that emitted warnings.
            num_error (Optional[int]): The number of dbt nodes (models) that emitted errors.
            num_skip (Optional[int]): The number of dbt nodes (models) that were skipped.
            num_total (Optional[int]): The total number of dbt nodes (models) that were processed.
        """
        super().__init__(*args, **kwargs)

        check.str_param(command, "command")
        check.int_param(return_code, "return_code")
        check.str_param(raw_output, "raw_output")
        check.opt_int_param(num_pass, "num_pass")
        check.opt_int_param(num_warn, "num_warn")
        check.opt_int_param(num_error, "num_error")
        check.opt_int_param(num_skip, "num_skip")
        check.opt_int_param(num_total, "num_total")

        self._command = command
        self._return_code = return_code
        self._raw_output = raw_output
        self._num_pass = num_pass
        self._num_warn = num_warn
        self._num_error = num_error
        self._num_skip = num_skip
        self._num_total = num_total

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "DbtCliResult":
        """Constructs an instance of :class:`DbtCliResult <dagster_dbt.DbtCliResult>` from a
        dictionary.

        Args:
            d (Dict[str, Any]): a dictionary with key-values to construct a :class:`DbtCliResult
                <dagster_dbt.DbtCliResult>`.

        Returns:
            DbtCliResult: an instance of :class:`DbtCliResult <dagster_dbt.DbtCliResult>`.
        """
        # check.int_elem(d, "return_code") TODO[Bob]: Implement `check.int_elem`.
        check.str_elem(d, "raw_output")
        # check.opt_int_elem(d, "num_pass") TODO[Bob]: Implement `check.opt_int_elem`.
        # check.opt_int_elem(d, "num_warn")
        # check.opt_int_elem(d, "num_error")
        # check.opt_int_elem(d, "num_skip")
        # check.opt_int_elem(d, "num_total")

        DbtResult.from_dict(d)  # Run the type checks for parent class, but throw away the instance.

        return cls(**d)

    @property
    def command(self) -> str:
        """str: The full shell command that was executed."""
        return self._command

    @property
    def return_code(self) -> int:
        """int: The return code of the dbt CLI process."""
        return self._return_code

    @property
    def raw_output(self) -> str:
        """str: The raw output (``stdout``) of the dbt CLI process."""
        return self._raw_output

    @property
    def num_pass(self) -> Optional[int]:
        """Optional[int]: The number of dbt nodes (models) that passed."""
        return self._num_pass

    @property
    def num_warn(self) -> Optional[int]:
        """Optional[int]: The number of dbt nodes (models) that emitted warnings."""
        return self._num_warn

    @property
    def num_error(self) -> Optional[int]:
        """Optional[int]: The number of dbt nodes (models) that emitted errors."""
        return self._num_error

    @property
    def num_skip(self) -> Optional[int]:
        """Optional[int]: The number of dbt nodes (models) that were skipped."""
        return self._num_skip

    @property
    def num_total(self) -> Optional[int]:
        """Optional[int]: The total number of dbt nodes (models) that were processed."""
        return self._num_total
